FROM python:3.12-slim

# Imposta cartella di lavoro
WORKDIR /flask_app

# Copia i file
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Espone la porta (5000 per Flask)
EXPOSE 5000

# Avvia il server Flask
CMD CMD ["flask", "run", "--host=0.0.0.0"]
