FROM python:3.10-slim

# Imposta cartella di lavoro
WORKDIR /flask_app

# Copia i file
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend/ .

# Espone la porta (5000 per Flask)
EXPOSE 5000

# Avvia il server Flask
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"] 
