// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUsOMz8XqFJqoAa1SGuAVeHE4ZKftkDIc',
    appId: '1:868691487287:web:e3cadb43a4cdd31b39adb2',
    messagingSenderId: '868691487287',
    projectId: 'hack-ai-thon-univpm',
    authDomain: 'hack-ai-thon-univpm.firebaseapp.com',
    storageBucket: 'hack-ai-thon-univpm.firebasestorage.app',
    measurementId: 'G-PC1GY58MRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-E5Cl0lYEUEaiiXqQC2UF5NKlXWbdrc',
    appId: '1:868691487287:android:98ae83176c4b700c39adb2',
    messagingSenderId: '868691487287',
    projectId: 'hack-ai-thon-univpm',
    storageBucket: 'hack-ai-thon-univpm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ryI4Trrhdt9oWuK_YDo9Dv67W5W-XwM',
    appId: '1:868691487287:ios:226366e95600729539adb2',
    messagingSenderId: '868691487287',
    projectId: 'hack-ai-thon-univpm',
    storageBucket: 'hack-ai-thon-univpm.firebasestorage.app',
    iosBundleId: 'com.example.provaFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ryI4Trrhdt9oWuK_YDo9Dv67W5W-XwM',
    appId: '1:868691487287:ios:226366e95600729539adb2',
    messagingSenderId: '868691487287',
    projectId: 'hack-ai-thon-univpm',
    storageBucket: 'hack-ai-thon-univpm.firebasestorage.app',
    iosBundleId: 'com.example.provaFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUsOMz8XqFJqoAa1SGuAVeHE4ZKftkDIc',
    appId: '1:868691487287:web:1c14bc19d67c5c3039adb2',
    messagingSenderId: '868691487287',
    projectId: 'hack-ai-thon-univpm',
    authDomain: 'hack-ai-thon-univpm.firebaseapp.com',
    storageBucket: 'hack-ai-thon-univpm.firebasestorage.app',
    measurementId: 'G-T7V571MF2S',
  );
}
