"""empty message

Revision ID: e7f2a369e2c2
Revises: 
Create Date: 2025-03-27 14:41:46.873519

"""
from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f2a369e2c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowbase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowbase')
    # ### end Alembic commands ###
